### PR TITLE
bumps dependencies and removes vulnerability caused by apache httpclient

### PR DESCRIPTION
**Pull request by The-Funk**
Excluded vulnerable commons-codec version from old Apache client and overrode with new version
Moved Jackson to 2.15.2, current version supported by Databricks 14.2 GA
Moved slf4j back to 1.7.36 (newer and better maintained than 1.8 series)
Bump other dependencies within minor version release train

### CODE REVIEW

**Comment by yogilad** [comment]
@ag-ramachandran , can you have a look at this contrinuted version bump PR?
Does this affect our compatibility with Synapse, Databricks, Fabric Spark?

**Comment by ohadbitt** [comment]
> @ag-ramachandran , can you have a look at this contrinuted version bump PR? Does this affect our compatibility with Synapse, Databricks, Fabric Spark?

I'm OK with it - Jackson 2.15.2 also updated in latest ADB

**Review by ohadbitt — APPROVED** [review]

**Comment by ohadbitt** [comment]
Seems like you need to run the formatter plugin

**Comment by The-Funk** [comment]
> Seems like you need to run the formatter plugin

Can do! How do I run the plugin?

**Comment by AsafMah** [comment]
@The-Funk 
If you have intellij you can access it from the maven menu:
image


Otherwise you can run (with the same maven you run other commands):
```bash
mvn formatter:format
``

**Comment by The-Funk** [comment]
I ran the formatter plugin however git is indicating no changes. The Java 8 build above is failing due to a dependency issue in the data module however the only thing that was changed directly in the data module was to use the newer commons-codec to replace the one that had the vulnerability.

I will look at the output of the build above a little more closely. The project compiles on my system and all the tests except E2E pass.

**Comment by yogilad** [comment]
Hi @ag-ramachandran , 

Would this PR cause any conflict with one or more of the Spark connector flavors?
If it does not, we'd like to approve it?
Otherwise, let's talk.

**Comment by ag-ramachandran** [comment]
The version looks okay @yogilad , it should be compatible

**Comment by yihezkel** [comment]
@ohadbitt @AsafMah
This PR seems to be triggering maven-dependency-plugin failures on:
Unused declared dependencies found: commons-codec:commons-codec:jar:1.16.0:compile

Are you sure it's being used in kusto-data?

In the meantime, I'm going to remove it in a PR I'm working on (https://github.com/Azure/azure-kusto-java/pull/341), and if you aren't aware of why we might need it, I'll proceed with merging that PR with the dependency removed.

**Comment by The-Funk** [comment]
@yihezkel it was used in kusto-ingest previously but might not be used anymore at all.

The Apache HTTP Client brings in an old version of it as a transitive dependency, so I had explicitly replaced it because the old version has some associated CVEs.

**Pull request merged**
